/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.eidansoft.sqlguia.formularios;

import com.eidansoft.sqlguia.ConfiguracionBD;
import com.eidansoft.sqlguia.FuncionesComunesDeArchivos;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.StreamException;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alorente
 */
public abstract class ConfiguracionesBD extends javax.swing.JFrame {

    /**
     * Variables globales
     */
    private List<ConfiguracionBD> configuraciones = new ArrayList<ConfiguracionBD>();
    private String archivoConf = "./configuraciones.xml";
    
    /**
     * Creates new form ConfiguracionesBD
     */
    public ConfiguracionesBD() {
        initComponents();
        
        //Cargo las configuraciones del XML
        XStream xstream = new XStream(new DomDriver());
        xstream.alias("configuracion", ConfiguracionBD.class);
        File xmlFile = new File(archivoConf);
        try{
            configuraciones = (List<ConfiguracionBD>) xstream.fromXML(new FileInputStream(xmlFile));
        } catch (StreamException e) {
            String msg = "Parece que el archivo de configuracion de BDs no existe o esta corrupto, por lo que se va a crear uno nuevo.";
            Logger.getLogger(ConfiguracionesBD.class.getName()).log(Level.SEVERE, msg, e);
            JOptionPane.showMessageDialog(null, msg + e.getMessage());
            guardaArchivoConfiguracion();
        } catch (FileNotFoundException ex) {
            String msg = "Parece que el archivo de configuracion de BDs no existe o esta corrupto, por lo que se va a crear uno nuevo.";
            Logger.getLogger(ConfiguracionesBD.class.getName()).log(Level.SEVERE, msg, ex);
            JOptionPane.showMessageDialog(null, msg + ex.getMessage());
            guardaArchivoConfiguracion();
        }
        
        //Las muestro en la lista lstConexionesPrevias
        actualizaListaConfiguraciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstConexionesPrevias = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        txtSid = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPw = new javax.swing.JTextField();
        btnConecta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstConexionesPrevias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstConexionesPrevias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstConexionesPreviasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstConexionesPrevias);

        jLabel1.setText("Host:");

        txtHost.setText("192.168.1.1");

        jLabel2.setText("Puerto:");

        jLabel3.setText("SID:");

        jLabel4.setText("Usuario:");

        jLabel5.setText("Contraseña:");

        txtPort.setText("1521");

        txtSid.setText("myBD");

        txtUsuario.setText("test");

        txtPw.setText("test");

        btnConecta.setText("Conecta!");
        btnConecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectaActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre:");

        txtNombre.setText("Conexion de prueba");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConecta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPw, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHost))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPort))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSid))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectaActionPerformed
        ConfiguracionBD conf = new ConfiguracionBD();
        conf.setIp(txtHost.getText());
        conf.setPuerto(txtPort.getText());
        conf.setPw(txtPw.getText());
        conf.setSID(txtSid.getText());
        conf.setUsuario(txtUsuario.getText());
        conf.setNombre(txtNombre.getText());
        
        if (!configuraciones.contains(conf)){
            // Añade y guarda
            configuraciones.add(conf);
            guardaArchivoConfiguracion();
        }
        
        configuracionLista(conf);
        setVisible(false);
    }//GEN-LAST:event_btnConectaActionPerformed

    private void lstConexionesPreviasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstConexionesPreviasMousePressed
        int selRow = lstConexionesPrevias.getSelectedIndex();
        if(selRow != -1) {
            ConfiguracionBD c = configuraciones.get(selRow);
            
            if(evt.getClickCount() == 1) {
                if (evt.getButton() != MouseEvent.BUTTON1){ //Si haces clic con un boton que no sea el derecho
                    int dialogResult = JOptionPane.showConfirmDialog (null, "Elimino la configuracion '" + c.getNombre(),"Warning", JOptionPane.YES_NO_OPTION);
                    if(dialogResult == JOptionPane.YES_OPTION){
                        configuraciones.remove(c);
                        guardaArchivoConfiguracion();
                        actualizaListaConfiguraciones();
                    }
                }
            }
            else if(evt.getClickCount() == 2) {
                txtHost.setText(c.getIp());
                txtPort.setText(c.getPuerto());
                txtPw.setText(c.getPw());
                txtSid.setText(c.getSID());
                txtUsuario.setText(c.getUsuario());
                txtNombre.setText(c.getNombre());
            }
        }
    }//GEN-LAST:event_lstConexionesPreviasMousePressed

    public abstract void configuracionLista(ConfiguracionBD configuracionSeleccionada);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConecta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstConexionesPrevias;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtPw;
    private javax.swing.JTextField txtSid;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void guardaArchivoConfiguracion() {
        XStream xstream = new XStream(new DomDriver());
        xstream.alias("configuracion", ConfiguracionBD.class);
        String xml = xstream.toXML(configuraciones);
        StringBuilder sb = new StringBuilder();

            sb.append("<?xml version=\"1.0\"?>\n"); //write XML header, as XStream doesn't do that for us
            sb.append(xml);
            FuncionesComunesDeArchivos.guardaArchivo(archivoConf, sb.toString());
    }

    private void actualizaListaConfiguraciones() {
        lstConexionesPrevias.removeAll();
        DefaultListModel<ConfiguracionBD> listaConfiguraciones = new DefaultListModel<ConfiguracionBD>();
        Iterator<ConfiguracionBD> it = configuraciones.iterator();
        while (it.hasNext()) {
            ConfiguracionBD configuracionBD = it.next();
            listaConfiguraciones.addElement(configuracionBD);
        }
        lstConexionesPrevias.setModel(listaConfiguraciones);
        lstConexionesPrevias.updateUI();
    }
}
